[package]
name = "cli"
version = "0.1.0"
authors = ["Stefan Lemvig Frederiksen <stefanlemvigfrederiksen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.suffix_tree]
path = "../suffix_tree"

[dev-dependencies]
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"